server:
  port: 8086
  shutdown: graceful

spring:
  application:
    name: simulator
  lifecycle:
    timeout-per-shutdown-phase: 30s
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}

management:
  endpoints:
    web:
      exposure:
        include: health,info
