version: '3.9'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-swifteats}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-swifteats}
      POSTGRES_DB: ${POSTGRES_DB:-swifteatsdb}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: swifteats-gateway:local
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    image: swifteats-order-service:local
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - rabbitmq
    environment:
  - POSTGRES_HOST=postgres
  - POSTGRES_DB=${POSTGRES_DB:-swifteatsdb}
  - POSTGRES_USER=${POSTGRES_USER:-swifteats}
  - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-swifteats}
  - RABBITMQ_HOST=rabbitmq
  - RABBITMQ_USER=${RABBITMQ_USER:-guest}
  - RABBITMQ_PASS=${RABBITMQ_PASS:-guest}
  - SECURITY_DEV_JWT_ENABLED=true

volumes:
  postgres_data:
