server:
  port: 8085

spring:
  application:
    name: tracking-query-service

spring:
  redis:
    host: ${REDIS_HOST:-redis}
    port: ${REDIS_PORT:-6379}

management:
  endpoints:
    web:
      exposure:
        include: health,info
