server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:-postgres}:5432/${POSTGRES_DB:-swifteatsdb}
    username: ${POSTGRES_USER:-swifteats}
    password: ${POSTGRES_PASSWORD:-swifteats}
  rabbitmq:
    host: ${RABBITMQ_HOST:-rabbitmq}
    username: ${RABBITMQ_USER:-guest}
    password: ${RABBITMQ_PASS:-guest}
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info
