server:
  port: 8085
  shutdown: graceful

spring:
  application:
    name: tracking-query-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  redis:
    host: ${REDIS_HOST:-redis}
    port: ${REDIS_PORT:-6379}

management:
  endpoints:
    web:
      exposure:
        include: health,info
