server:
  port: 8084

spring:
  application:
    name: tracking-ingest-service

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:-rabbitmq}
    username: ${RABBITMQ_USER:-guest}
    password: ${RABBITMQ_PASS:-guest}

management:
  endpoints:
    web:
      exposure:
        include: health,info
