server:
  port: 8084
  shutdown: graceful

spring:
  application:
    name: tracking-ingest-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  rabbitmq:
    host: ${RABBITMQ_HOST:-rabbitmq}
    username: ${RABBITMQ_USER:-guest}
    password: ${RABBITMQ_PASS:-guest}

management:
  endpoints:
    web:
      exposure:
        include: health,info
