name: Gateway Unit Tests & Coverage

on:
  push:
    paths:
      - 'gateway/**'
  pull_request:
    paths:
      - 'gateway/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run gateway unit tests and JaCoCo
        run: |
          ./mvnw -pl :gateway -DskipTests=false -B verify -DskipITs

      - name: Upload JaCoCo HTML report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: gateway-jacoco-report
          path: gateway/target/site/jacoco

      - name: Upload JaCoCo exec
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: gateway-jacoco-exec
          path: gateway/target/jacoco.exec
